name: Bad CI Pipeline

on:
  push:
    branches:
      - Bad-CICD

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'

      - name: Run Tests
        run: mvn test

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'

      - name: Install and start Tomcat
        run: |
          sudo apt-get install -y tomcat9
          sudo systemctl start tomcat9
          sudo systemctl status tomcat9

      - name: Deploy Application
        run: mvn clean deploy
