name: Common Steps

on:
  workflow_call:
    inputs:
      java_version: true
      type: string
jobs:
  common-steps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ inputs.java_version }}
          distribution: 'adopt'