name: Good CI Pipeline

on:
  push:
    branches:
      - Good-CICD

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'

  build:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 18
        uses: actions/setup-java@v2
        with:
          java-version: '18'
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Build with Maven
        run: mvn clean package

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Tomcat
        run: |
          sudo add-apt-repository universe
          sudo apt-get update
          sudo apt-get install -y tomcat9 tomcat9-admin tomcat9-common

      - name: Cache Tomcat installation
        uses: actions/cache@v2
        with:
          path: /var/lib/tomcat9
          key: ${{ runner.os }}-tomcat

      - name: Start Tomcat
        run: |
          sudo systemctl start tomcat9
          sudo systemctl status tomcat9

      - name: Deploy to Tomcat
        run: mvn tomcat7:deploy
        env:
          MAVEN_OPTS: "-Dtomcat.url=http://localhost:8080/manager/text \
                       -Dtomcat.username=${{ secrets.USERNAME }} \
                       -Dtomcat.password=${{ secrets.TOMCAT_PASSWORD }}"

  test:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Tests
        run: mvn test
